application:
  version: 0.1.3
  initDB: true

security:
  jwt:
    token:
      expireHours: 1460
      secret-key: dnsjndajksnjxnsajn6786

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: xflj1sll^jc1k7vt
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: gqx90291
  jpa:
    hibernate:
      ddl-auto: create