application:
  version: 0.3.7
  initDB: true

security:
  jwt:
    token:
      expireHours: 1460
      secret-key: dnsjndajksnjxnsajn6786

spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    password: qbk13bb2wcf@3wls
    url: jdbc:db2://dashdb-txn-sbox-yp-lon02-02.services.eu-gb.bluemix.net:50000/BLUDB
    username: bbk78600
  jpa:
    properties:
      hibernate: org.hibernate.dialect.DB2Dialect
    hibernate:
      ddl-auto: create