application:
  version: 0.2.5
  initDB: true

security:
  jwt:
    token:
      expireHours: 1460
      secret-key: dnsjndajksnjxnsajn6786

spring:
  datasource:
    hikari:
      max-active: 5
    max-active: 5
    tomcat:
      max-active: 5
    driver-class-name: org.postgresql.Driver
    password: ul9yp8hclPjOodBl
    url: jdbc:postgresql:///postgres?cloudSqlInstance=freezer-276212:europe-west1:postgredb&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=ul9yp8hclPjOodBl
    username: postgres
  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create